jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet build and test
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - run: dotnet build
      - run: dotnet test